title:              NETN Pathfinder Lodge
email:              netnpathfinder@gmail.com
description:        The NETN Pathfinder Society lodge strives to bring together TTRPG gamers from Johnson City, Kingpost, Blountville, Erwin, Elizabethton, and even Mountain City, TN in a fun, friendly role-playing environment.
author:             NETN Pathfinder Lodge
baseurl:            "/"
url:                "https://netnpathfinder.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-147154958-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
